name: ghpage

on:
  workflow_dispatch:
  push:
    paths:
      - 'nav.csv'

jobs:
  job:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
  
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - run: |
          mv nav.csv index.html
          sed -E '/^,/d' index.html -i

      - run: |
          sed -E 's@^([^#].*.?),(.*)@<a href=//\1>\2</a>@g' index.html -i
          sed -E 's@^#,(.*)@<h2>\1</h2>@g' index.html -i
          echo '<meta name=viewport content=width=device-width,initial-scale=1>' >> index.html
          echo '<base target=_blank>' >> index.html
          echo '<style>a{margin-right:15;display:inline-block}@media(prefers-color-scheme:dark){html{background:#121212;color:#fff}a{color:#9e9eff}a:visited{color:#d0adf0}}' >> index.html
          sed ':a;N;s/\n//g;ta' index.html -i

      - run: |
          mkdir dist
          mv index.html dist
          echo -e '[[headers]]\nfor = "/*"\n[headers.values]\ncache-control = "public, max-age=86400"' > netlify.toml

      - env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_SHU }}
        run: |
          npm install -g netlify-cli
          netlify link
          netlify build
          netlify deploy --dir=dist --prod

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - id: deployment
        uses: actions/deploy-pages@v4
