name: ghpage

on:
  workflow_dispatch:
  push:
    paths:
      - 'README.md'

jobs:
  job:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
  
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: run
        run: |
          curl -L https://github.com/nibazshab/shu/raw/main/README.md > index.html
          sed -E '/(<!--|-->)/d' -i index.html
          sed -E 's@(^//.*.?),(.*)@<a href=\1 target=_blank>\2</a>@g' -i index.html
          sed -E 's@^> (.*)@<h2>\1</h2>@g' -i index.html
          echo '<meta name=viewport content=width=device-width,initial-scale=1>' >> index.html
          echo '<style>a{margin-right:15px;display:inline-block}@media(prefers-color-scheme:dark){html{background-color:#000000;color:#ffffff;}a{color:#ffff11;}a:visited{color:#aae574;}}</style>' >> index.html
          sed ':a;N;s/\n//g;ta' -i index.html

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v4

      - name: post
        run: sleep 3 && curl -X POST ${{ secrets.SECRET }}
